<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="143" started-at="2019-08-11T08:10:38Z" finished-at="2019-08-11T08:10:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="143" started-at="2019-08-11T08:10:38Z" finished-at="2019-08-11T08:10:38Z">
      <class name="com.Login">
        <test-method status="FAIL" signature="login_email()[pri:0, instance:com.Login@591f989e]" name="login_email" duration-ms="31" started-at="2019-08-11T13:40:38Z" finished-at="2019-08-11T13:40:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[test cases passed... expected [Firefox] but found [firefox]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: test cases passed... expected [Firefox] but found [firefox]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.Login.login_email(Login.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_email -->
        <test-method status="PASS" signature="login_email2()[pri:0, instance:com.Login@591f989e]" name="login_email2" duration-ms="3" started-at="2019-08-11T13:40:38Z" finished-at="2019-08-11T13:40:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_email2 -->
        <test-method status="PASS" signature="login_email3()[pri:0, instance:com.Login@591f989e]" name="login_email3" duration-ms="6" started-at="2019-08-11T13:40:38Z" finished-at="2019-08-11T13:40:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_email3 -->
        <test-method status="FAIL" signature="login_facebook()[pri:0, instance:com.Login@591f989e]" name="login_facebook" duration-ms="2" started-at="2019-08-11T13:40:38Z" finished-at="2019-08-11T13:40:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [firefox] but found [Firefox]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [firefox] but found [Firefox]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.Login.login_facebook(Login.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_facebook -->
        <test-method status="PASS" signature="login_google()[pri:0, instance:com.Login@591f989e]" name="login_google" duration-ms="6" started-at="2019-08-11T13:40:38Z" finished-at="2019-08-11T13:40:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_google -->
      </class> <!-- com.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
